#!/usr/bin/env bash

## lscript 3.1 - log-oriented emulation for FreeBSD script(1)
## w/ additional logging output and tai64n integration
##

_echo_hdr="echo -n \"#-- \""

if [ -z "${ANNOTATE}" ]; then
  ## NB: tai64n is available in pkgsrc PKGPATH=sysutils/daemontools
  ANNOTATE=$(which tai64n)
  if [ -z "${ANNOTATE}" ]; then
    ANNOTATE=${CAT:-cat}
  fi
fi

_OUTF="$1"; shift

_CMD="$*"

_SCRIPT_CMD="${_echo_hdr}; echo ${_CMD};
 ${_echo_hdr}; uname -a; ${_echo_hdr}; pwd;
 ${_echo_hdr}; date; ${_echo_hdr}; echo \${SHELL};
 exec ${_CMD} 2>&1 | ${ANNOTATE}"

case $(uname -o) in
    FreeBSD)
        SCRIPT=${SCRIPT:-$(which script)}
    ;;
    *)
      SCRIPT=${SCRIPT:-$(which nb-script)}
      if [ -z "${SCRIPT}" ]; then
        SCRIPT=${SCRIPT:-$(which script)}
        if [ -z "${SCRIPT}" ]; then
          _THIS=$(basename $(readlink -f "$0"))
          echo "#-- ${_THIS}: cannot find nb-script or script in PATH" 1>&2
          exit 1
        fi
      fi
    ;;
esac

## NB: objects in the echo(1) output may not be as they appear to exec(3)

case $(uname -o) in
    FreeBSD)
        ## FreeBSD script(1)
        ## whence "-t 0" is analogous to nb-script(1) "-f"
        exec "${SCRIPT}" -t 0 "${_OUTF}" "${SHELL}" -c "${_SCRIPT_CMD}"
    ;;
    *)
        exec "${SCRIPT}" -f -c "${_SCRIPT_CMD}" "${_OUTF}"
    ;;
esac
