# Makefile - mk_sysroot sh_pkg                          -*- makefile-bsdmake -*-

PKG_SHELL_FILES+=pkg_shell.sh
PKG_SHELL_FILES+=pkg_distname
PKG_SHELL_FILES+=pkg_name
PKG_SHELL_FILES+=pkg_name_versioned
PKG_SHELL_FILES+=pkg_pkgpath
PKG_SHELL_FILES+=pkg_depends

SYS_FILES+=	bashrc_pkg.sh

MISC_FILES+=	finish_bootstrap.sh
MISC_FILES+=	pkg_install_fonts.sh
