#!/usr/bin/env bash

## NB
# bash ./pkg_pkgpath verifypc

_THIS_P=$(readlink -f "$0")
_HERE=$(dirname "${_THIS_P}")
_THIS=$(basename "${_THIS_P}")

. "${_HERE}/pkg_shell.sh"

_pkg_path_p "${1:-$PWD}"
